routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

Route::get('/', 'OpratorAuth\LoginController@showLoginForm')->name('login');
Route::get('/get/Doctors/today', 'OpratorController@getDoctors');

Route::group(['prefix' => 'oprator'], function () {
      Route::post('/login', 'OpratorAuth\LoginController@login');
      Route::post('/logout', 'OpratorAuth\LoginController@logout')->name('logout');
      Route::post('/delete/{id}', 'OpratorController@delete')->name('Oprator.delete');
      Route::get('/home', 'OpratorController@showHome')->name('Oprator.Home');

      Route::get('/register', 'OpratorAuth\RegisterController@showRegistrationForm')->name('oprator.register');
      Route::post('/register', 'OpratorAuth\RegisterController@register');
});

Route::group(['prefix' => 'admin'], function () {
      Route::get('/', 'AdminAuth\LoginController@showLoginForm')->name('AdminLogin');
      Route::post('/login', 'AdminAuth\LoginController@login');
      Route::post('/logout', 'AdminAuth\LoginController@logout')->name('AdminLogout');

      Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('admin.register');
      Route::post('/register', 'AdminAuth\RegisterController@register');
});

Route::resource('doctor', 'DoctorController');
Route::get('/get/Doctors', 'DoctorController@getDoctors');
Route::get('/get/Doctors/withSpecialityId/{id}', 'DoctorController@getDoctorsWithSpecialityId');

Route::resource('specialist', 'SpecialistController');
Route::get('/get/Specialitys', 'SpecialistController@getSpecialitys');

Route::resource('off', 'OffController');

Route::resource('patient', 'PatientController')->except('destroy');
Route::post('/patient/{id}', 'PatientController@destroy');
Route::get('/get/patients/{date}/{docId}', 'PatientController@getPatientWithDate');
Route::get('/patient/done/{id}', 'PatientController@patientDone');

Route::resource('work-time', 'WorkTimeController');

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
      /**
       * The database table used by the model.
       *
       * @var string
       */
      protected $table = 'doctors';

      /**
       * The database primary key value.
       *
       * @var string
       */
      protected $primaryKey = 'id';

      /**
       * Attributes that should be mass-assignable.
       *
       * @var array
       */
      protected $fillable = ['name', 'phone_number', 'specialist_id'];

      public function speciality()
      {
            return $this->belongsTo('App\Specialist','specialist_id' );
      }

      public function workTime()
      {
            return $this->hasMany('App\WorkTime','dr_id' );
      }
      public function off()
      {
            return $this->hasMany('App\Off','dr_id' );
      }

}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Doctor;
use App\Specialist;
use Illuminate\Http\Request;

class DoctorController extends Controller
{
      public function __construct()
      {
            $this->middleware('admin')->except('getDoctors' ,'getDoctorsWithSpecialityId');
      }

      public function getDoctors()
      {
            $Doctors = Doctor::get()->all();
            return $Doctors;
      }

      public $days = [
            'شنبه' , 'یکشنبه' , 'دوشنبه' , 'سه شنبه' , 'چهارشنبه' , 'پنجشنبه' , 'جمعه'
      ];


      /**
       * Display a listing of the resource.
       *
       * @return \Illuminate\View\View
       */
      public function index(Request $request)
      {
            $keyword = $request->get('search');
            $perPage = 25;

            if (!empty($keyword)) {
                  $doctor = Doctor::where('name', 'LIKE', "%$keyword%")
                                             ->latest()->paginate($perPage);
            } else {
                  $doctor = Doctor::latest()->paginate($perPage);
            }
            return view('doctor.index', compact('doctor'));
      }

      public function getDoctorsWithSpecialityId($specialityId)
      {
            $speciality = Doctor::where('specialist_id',$specialityId)->get()->all();
            return $speciality;
      }
      /**
       * Show the form for creating a new resource.
       *
       * @return \Illuminate\View\View
       */
      public function create()
      {
            $specialitys = Specialist::all();
            return view('doctor.create' , compact('specialitys' , 'days'));
      }

      /**
       * Store a newly created resource in storage.
       *
       * @param \Illuminate\Http\Request $request
       *
       * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
       */
      public function store(Request $request)
      {
            $requestData = $request->all();
            
            $validatedData = $request->validate([
                  'name' => 'required|min:4|max:255|unique:doctors',
                  'phone_number' => 'required|min:7|max:14|unique:doctors',
            ]);

            Doctor::create($requestData);
            return redirect(route('work-time.index'))->with('flash_message', 'Doctor added!');
      }

      /**
       * Display the specified resource.
       *
       * @param  int  $id
       *
       * @return \Illuminate\View\View
       */
      public function show($id)
      {
            $doctor = Doctor::findOrFail($id);

            return view('doctor.show', compact('doctor'));
      }

      /**
       * Show the form for editing the specified resource.
       *
       * @param  int  $id
       *
       * @return \Illuminate\View\View
       */
      public function edit($id)
      {
            $doctor = Doctor::findOrFail($id);
            $specialitys = Specialist::all();
            return view('doctor.edit', compact('doctor' , 'specialitys'));
      }

      /**
       * Update the specified resource in storage.
       *
       * @param \Illuminate\Http\Request $request
       * @param  int  $id
       *
       * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
       */
      public function update(Request $request, $id)
      {

            $requestData = $request->all();

            $doctor = Doctor::findOrFail($id);
            $doctor->update($requestData);

            return redirect('doctor')->with('flash_message', 'Doctor updated!');
      }

      /**
       * Remove the specified resource from storage.
       *
       * @param  int  $id
       *
       * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
       */
      public function destroy($id)
      {
            Doctor::destroy($id);

            return redirect('doctor')->with('flash_message', 'Doctor deleted!');
      }
}

resources/views/doctor/create.blade.php
@extends('admin.layout.auth')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-3">
            </div>
            <div class="col-md-8" id="creaeteDoc">
                    <br />
                    <br />
                <div class="card">
                    <div class="card-header text-center">اضافه کردن دکتر جدید</div>
                    <div class="card-body">
                            <br />
                            <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::open(['url' => '/doctor', 'class' => 'form-horizontal', 'files' => true]) !!}
                        <br>
                        @include ('doctor.form')

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
            <div class="col-md-3"> </div>
        </div>
    </div>
@endsection
@section('js')
    <script></script>
@endsection

resources/views/doctor/edit.blade.php
@extends('admin.layout.auth')

@section('content')
      <div class="container">
            <div class="row">

                  <div class="col-md-12">
                        <div class="card">
                              <div class="card-header col-lg-offset-5 ">
                                    <h2>
                                          {{ $doctor->name }} #
                                    </h2>
                              </div>
                              <div class="card-body col-lg-offset-4">
                                    <a href="{{ url('/doctor') }}" title="Back">
                                          <button class="btn btn-warning btn-sm">
                                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
                                          </button>
                                    </a>
                                    <br />
                                    <br />

                                    @if ($errors->any())
                                          <ul class="alert alert-danger">
                                                @foreach ($errors->all() as $error)
                                                      <li>{{ $error }}</li>
                                                @endforeach
                                          </ul>
                                    @endif

                                    {!! Form::model($doctor, [
                                        'method' => 'PATCH',
                                        'url' => ['/doctor', $doctor->id],
                                        'class' => 'form-horizontal',
                                        'files' => true
                                    ]) !!}

                                    @include ('doctor.form', ['submitButtonText' => 'Update'])

                                    {!! Form::close() !!}

                              </div>
                        </div>
                  </div>
            </div>
      </div>
@endsection

resources/views/doctor/form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
      <div class="col-md-6">
            {!! Form::text('name', null, ('' == 'required') ? ['class' => 'form-control text-right', 'required' => 'required']
                                                                              : ['class' => 'form-control text-right']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
      </div>
      {!! Form::label('name', 'نام و نام خانوادگی', ['class' => 'control-label']) !!}

</div>
<div class="form-group {{ $errors->has('phone_number') ? 'has-error' : ''}}">
      <div class="col-md-6">
            {!! Form::number('phone_number', null, ('' == 'required') ? ['class' => 'form-control', 'required' => 'required'] : ['class' => 'form-control']) !!}
            {!! $errors->first('phone_number', '<p class="help-block">:message</p>') !!}
      </div>
      {!! Form::label('phone_number', 'شماره تلفن', ['class' => 'control-label']) !!}

</div>
<div class="form-group {{ $errors->has('specialist_id') ? 'has-error' : ''}}">
      <div class="col-md-6">
            <select name="specialist_id" class="form-control">
                  @foreach($specialitys as $speciality)
                        <option value="{{$speciality->id}}">{{$speciality->speciality}}</option>
                  @endforeach
            </select>
      </div>
      {!! Form::label('speciality', 'متخصص', ['class' => ' control-label']) !!}
</div>
<br>
<div class="form-group">
      <div class="col-md-offset-2 col-md-4">
            {!! Form::submit(isset($submitButtonText) ? $submitButtonText : 'Create', ['class' => 'btn btn-primary']) !!}
      </div>
</div>

resources/views/doctor/index.blade.php
@extends('admin.layout.auth')

@section('content')
      <div class="container">
            <br>
            <br>
            <br>
            <div class="row">
                  <div class="col-md-12">
                        <div class="card">
                              <div class="card-body ">
                                    <div class="row col-lg-offset-2">
                                          <div class="col-lg-2">
                                                <a href="{{ route('specialist.index') }}" class="btn btn-primary btn-sm" title="Add New Doctor">
                                                      <i class="fa fa-plus" aria-hidden="true"></i> اضافه کردن تخصص جدید
                                                </a>
                                          </div>
                                          <div class="col-lg-2">
                                                <a href="{{ route('doctor.create') }}" class="btn btn-success btn-sm" title="Add New Doctor">
                                                      <i class="fa fa-plus" aria-hidden="true"></i> اضافه کردن دکتر جدید
                                                </a>
                                          </div>
                                          <div class="col-md-4">
                                                {!! Form::open(['method' => 'GET', 'url' => '/doctor', 'class' => 'form-inline my-2 my-lg-0 float-right', 'role' => 'search'])  !!}
                                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                                <span class="input-group-append">
                                                    <button class="btn btn-secondary" type="submit">
                                                            <i class="fa fa-search"></i>                                    جستجو کن
                                                    </button>
                                                </span>
                                                {!! Form::close() !!}
                                          </div>
                                    </div>

                                    <br/>
                                    <br/>
                                    <div class="table-responsive">
                                          <table class="table table-borderless text-center">
                                                <thead>
                                                <tr>
                                                      <th class="text-center">#</th>
                                                      <th class="text-center">نام و نام خانوادگی</th>
                                                      <th class="text-center">روز های کاری</th>
                                                      <th class="text-center">شماره تلفن</th>
                                                      <th class="text-center">متخصص</th>
                                                      <th class="text-center">گزینه ها</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @foreach($doctor as $item)
                                                      <tr>
                                                            <td>{{ $loop->iteration or $item->id }}</td>
                                                            <td>{{ $item->name }}</td>
                                                            <td>@foreach($item->workTime as $time) {{$time->day .','}} @endforeach</td>
                                                            <td>{{ $item->phone_number }}</td>
                                                            <td>{{ $item->speciality->speciality }}</td>
                                                            <td>
                                                                  <a href="{{ url('/doctor/' . $item->id . '/edit') }}" title="Edit Doctor"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> تغییر</button></a>
                                                                  {!! Form::open([
                                                                      'method'=>'DELETE',
                                                                      'url' => ['/doctor', $item->id],
                                                                      'style' => 'display:inline'
                                                                  ]) !!}
                                                                  {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> حذف', array(
                                                                          'type' => 'submit',
                                                                          'class' => 'btn btn-danger btn-sm',
                                                                          'title' => 'Delete Doctor',
                                                                          'onclick'=>'return confirm("Confirm delete?")'
                                                                  )) !!}
                                                                  {!! Form::close() !!}
                                                            </td>
                                                      </tr>
                                                @endforeach
                                                </tbody>
                                          </table>
                                          <div class="pagination-wrapper"> {!! $doctor->appends(['search' => Request::get('search')])->render() !!} </div>
                                    </div>

                              </div>
                        </div>
                  </div>
            </div>
      </div>
@endsection

resources/views/doctor/show.blade.php
@extends('admin.layout.auth')

@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Doctor {{ $doctor->id }}</div>
                    <div class="card-body">
                        <a href="{{ url('/doctor') }}" title="OK"><button class="btn btn-success btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i>صحیح</button></a>
                        <a href="{{ url('/doctor/' . $doctor->id . '/edit') }}" title="Edit Doctor"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>
                        {!! Form::open([
                            'method'=>'DELETE',
                            'url' => ['doctor', $doctor->id],
                            'style' => 'display:inline'
                        ]) !!}
                        {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> Delete', array(
                                'type' => 'submit',
                                'class' => 'btn btn-danger btn-sm',
                                'title' => 'Delete Doctor',
                                'onclick'=>'return confirm("Confirm delete?")'
                        ))!!}
                        {!! Form::close() !!}
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <tbody>
                                {{--<tr>--}}
                                    {{--<th>ID</th><td>{{ $doctor->id }}</td>--}}
                                {{--</tr>--}}
                                <tr><th>نام و نام خانوادگی</th><td> {{ $doctor->name }} </td></tr>
                                <tr><th>شماره تلفن</th><td> {{ $doctor->phone_number }} </td></tr>
                                <tr><th>متخصص</th><td> {{ $doctor->speciality->speciality }} </td></tr>
                                @foreach($doctor->workTime as $work)
                                    <tr>
                                        <th> روز کاری </th>
                                        <td> {{ $work->day }} </td>
                                        <td> {{ $work->start }} </td>
                                        <td> {{ $work->end }} </td>
                                        <td></td>
                                    </tr>

                                @endforeach

                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection